name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Geode SDK
        run: |
          geode sdk install latest
          geode sdk install-binaries

      - name: Build mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          target: Windows

      - name: Copy .geode for release
        run: cp ./artifacts/geode-build-win/*.geode ./vesdi4.level-notes.geode

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: vesdi4.level-notes.geode
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}